[package]
name = "cyno"
version = "0.1.0"
authors = ["Chad Laing <chad.laing@canada.ca>"]
edition = "2018"

[dependencies]
bio = "0.25.0"
grpcio = { version = "0.4", default-features = false, features = ["protobuf-codec"] }
dgraph = "0.1.1"