[package]
name = "cyno"
version = "0.1.0"
authors = ["Chad Laing <chad.laing@canada.ca>"]
edition = "2018"

[dependencies]
bio = "0.25.0"
dgraph = "0.1.2"
blake2 = "0.8.0"
serde = "1.0.89"
serde_json = "1.0.39"
structopt = "0.2.15"
rayon = "1.0.3"



